### ISSUE TITLE
Counting only published blogs in series

### ISSUE THREAD

**Issue by exaline-ru** [GinoPane/oc-blogtaxonomy-plugin#25]
Posts-in-series component seems to be counting all posts instead of published posts only

**Comment by GinoPane** [comment]
Hi @exaline-ru! Thanks for reporting this!
Just to be on the same page, did you report the issue with post count when you display a series list via `seriesList` component? Because it counts fine and display posts properly for individual series via `postsInSeries` component.
I reproduced the issue with series list component and will fix that.
