### ISSUE TITLE
Question about Taglist search component

### ISSUE THREAD

**Issue by HitArrowLegend** [GinoPane/oc-blogtaxonomy-plugin#68]
Hello,

I was playing around with the TagList search component and found out that it was only working if the component was added to a page and not a partial. Is there a way to change this, or is it something that has to do with October itself?

The component itself works, but it seems the script is not taken into account. Clearly not a deal breaker as I just need to update some of my pages, but I was wondering what was happening for a bit ^^'

**Comment by GinoPane** [comment]
Hi!
The components itself uses injecting into %scripts%, which works only from pages/layouts: https://octobercms.com/docs/markup/tag-scripts. If you look at the component's partial, you could see:
![image](https://user-images.githubusercontent.com/3897579/83225900-709ab500-a189-11ea-9696-f69f02cb58d3.png)

The reason why it's done, that this component uses a small jQuery package under the hood, and jQuery must be loaded **before** this component's javascript. Themes by default put all scripts including jQuery to the **bottom** of the page.

So you could put this component in a partial and remove the logic which puts the javascript code into theme's scripts, but in this case you need to make sure to include the jQuery manually on the top of you pages. Because without it you'll simply get an error like this (wgich means that jQuery is not loaded yet): 

![image](https://user-images.githubusercontent.com/3897579/83226203-177f5100-a18a-11ea-8852-2d81a3292de1.png)

So, strictly speaking, it is possible to place it into the partial, but it will require some additional updates in you pages to make this work.

**Comment by GinoPane** [comment]
But! If your partial eventually ends up as part of some page, this component should also work probably, I've just tried to put it into one of my partials and it worked fine.

Maybe you have any JS errors in your case? Or anything else is preventing the scripts from being injected?

**Comment by HitArrowLegend** [comment]
I don't exactly know, but I have noticed that it didn't work from partials. I'm going to put the script somewhere else and see how it works :D

**Comment by HitArrowLegend** [comment]
Okay, I understood where the problem was coming from. It is fixed now :D, thanks

**Comment by HitArrowLegend** [comment]
Okay, I made it. I just removed, as you said, the put scripts and it works fine from partials as well. My Jquery is always on top, so this won't be an issue.

**Comment by GinoPane** [comment]
Yes, basically, it searches for tags in a list. The intention for it was to easily find required tag in a cloud if you have a lot of them (displayed on the page at the same time). So it does not looks for everything not visible if the limit is enabled.

Anyway, if it proves to be a real use-case, I can think about implementation.

**Comment by HitArrowLegend** [comment]
Okay I understand now, I wasn't sure if it was intended or not. 

On my website, I'll most likely have tons of tags (it's a website about metal bands, and there is ton of them). The way I planned to use the component was to have a list of 10 tags in the sidebar, the most active ones, and have this search go through the rest of them, if a visitor wanted to check an existing band. 

I'll just do differently, no problem :)

**Comment by GinoPane** [comment]
Yeah, for this case I personally use the "show all tags" link with a dedicated page with all of them :) 

P.S. Is it an active website or under development? I'm a metalhead too, so could check it out 🤘

**Comment by HitArrowLegend** [comment]
currently under dev, but I'll be sure to let you know when it's out :D. Mostly about prog bands tho.
