### ISSUE TITLE
[FEATURE REQUEST] - Add possibility to remove the series from the series list page

### ISSUE THREAD

**Issue by HitArrowLegend** [GinoPane/oc-blogtaxonomy-plugin#69]
**Describe the bug**
I cannot remove created series

**To Reproduce**
1. Create a blog serie
2. Try to remove it
3. No button
...

**Expected behavior**
I was expecting to have checkboxes to manage my series the same way tags work. 

**Screenshots**
https://puu.sh/FUXDQ/9fa114ab2e.png

**Comment by GinoPane** [comment]
@HitArrowLegend huh, it's funny and true 😄 
Anyway, I'll categorize this as feature request, because you still can delete series. Just open the series you want to delete and click trash icon in the right bottom corner:

![image](https://user-images.githubusercontent.com/3897579/84350772-9df05580-abc2-11ea-8d92-20639d634836.png)

**Comment by HitArrowLegend** [comment]
Oh wow, I didn't know ^^' Thanks for pointing that out

**Comment by GinoPane** [comment]
Please check out 2.3.0 version
