### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Exodon** [GinoPane/oc-blogtaxonomy-plugin#80]
**Describe the bug**
Opened the backend of the october cms. Got a notification that was an update available. I confirm to update your plugin. After that front end stop working and nothing appear.
**I checked the logs** 
Symfony\Component\Debug\Exception\FatalErrorException: Declaration of GinoPane\BlogTaxonomy\Components\TagPosts::prepareVars(): GinoPane\BlogTaxonomy\Components\void must be compatible with GinoPane\BlogTaxonomy\Classes\PostListAbstract::prepareVars(): GinoPane\BlogTaxonomy\Classes\void in /home/didgenat/public_html/portal/plugins/ginopane/blogtaxonomy/components/TagPosts.php:15

In case I disable the plugin, everything's work fine.

**To Reproduce**
1. Update the plugin based on the latest version ( 2.6.0)
2. checked the website and everything stop working
3. Only in case I disable the plugin the website works fine.
...

**Expected behavior**
After an update everything should work as previously

**Comment by GinoPane** [comment]
@Exodon hi! Thanks for reporting this. 

What version of PHP do you have? Is it lower than PHP7.2?

As you see the declaration is the same everywhere:
![image](https://user-images.githubusercontent.com/3897579/98781706-d90fe280-2407-11eb-8a19-8e1c510d0038.png)

The problem is that probably you are using too old PHP version. 

The October itself requires at least PHP 7.2:

![image](https://user-images.githubusercontent.com/3897579/98781803-0066af80-2408-11eb-8eab-fbf33f81b7e7.png)

I will place a fix on my end anyway.

**Comment by GinoPane** [comment]
@Exodon please update to 2.6.1

**Comment by Exodon** [comment]
thanks @GinoPane for the quick fix. Yes I have a version lower then 7.2. I need to update that. I´m going to test your fix.

**Comment by Exodon** [comment]
is working fine....tks

**Comment by GinoPane** [comment]
I was mistaken when thinking that PHP 7.2 is required for the released version of October. Actually, it is only for its development version and probably it will be required in the next major release.

**Comment by Exodon** [comment]
cool good to know
